### ISSUE TITLE
Remove / Ignore unneeded files

### ISSUE THREAD

**Issue by lionkor** [sla-ppy/street-game#1]
`src/street-game` and `.vscode` as well as `src/.vscode` etc. shouldn't be in the repository. 

suggesting to remove them add them to .gitignore, i can open a pull request for that if it helps.

**Comment by sla-ppy** [comment]
> re, i can open a pull request for that if it helps.

please do, because i'd like to see what that looks like.
thanks you fren for the suggestion, fixed! <3

**Comment by lionkor** [comment]
Hi, looks like your new [.gitignore](https://github.com/S4kyt/street-game/blob/dev/.gitignore) already includes everything you need :) no need for a PR.
